on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: A multi os runner

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install python requirements
        run: python -m pip install pyinstaller -r requirements.txt

      - name: Install librairies
        run: python setup-libraries.py

      - name: Bundling the executable
        run: pyinstaller --onefile src/main.py

      - name: Packing the executable
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir ie-gcs-undub-linux
          mkdir ie-gcs-undub-linux/lib
          mv dist/main ie-gcs-undub-linux/main
          mv .env ie-gcs-undub-linux/.env
          mv lib/* ie-gcs-undub-linux/lib
          zip -r ie-gcs-undub-linux.zip ie-gcs-undub-linux/

      - name: Packing the executable
        if: matrix.os == 'macos-latest'
        run: |
          mkdir ie-gcs-undub-macos
          mkdir ie-gcs-undub-macos/lib
          mv dist/main ie-gcs-undub-macos/main
          mv .env ie-gcs-undub-macos/.env
          mv lib/* ie-gcs-undub-macos/lib
          zip -r ie-gcs-undub-macos.zip ie-gcs-undub-macos/

      - name: Archive Linux binary artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ie-gcs-undub-linux
          path: ie-gcs-undub-linux

      - name: Archive MacOS binary artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ie-gcs-undub-macos
          path: ie-gcs-undub-macos