on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: An ubuntu runner
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install python requirements
        run: python -m pip install pyinstaller -r requirements.txt

      - name: Install librairies
        run: python setup-libraries.py

      - name: Bundling the executable
        run: pyinstaller --onefile src/main.py

      - name: Packing the executable
        run: |
          mkdir ie-gcs-undub-linux
          mkdir ie-gcs-undub-linux/lib
          mv dist/main ie-gcs-undub-linux/main
          mv .env ie-gcs-undub-linux/.env
          mv lib/* ie-gcs-undub-linux/lib
          zip -r ie-gcs-undub-linux.zip ie-gcs-undub-linux/

      - name: Archive linux binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: ie-gcs-undub-linux
          path: ie-gcs-undub-linux