on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: An ubuntu runner
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install python requirements
        run: python -m pip install -r requirements.txt

      - name: Install librairies
        run: python setup-librairies.py